#!/bin/zsh

source config

OPERATION=$1

REGISTRY=demo/alice/registry.json

dkg() {
    section "🔑 Post invite for DKG group to Hubert '$STORAGE'..."

    INVITE_ARID=$(\
        frost dkg coordinator invite \
        --storage $STORAGE \
        --registry "$REGISTRY" \
        --min-signers 2 \
        --charter "This group will authorize new club editions." \
        Bob Carol Dan\
    )
    echo "\n\n${INVITE_ARID}\n"

    section "🔑 Collect Round 1 responses and dispatch Round 2 for DKG group.."

    GROUP_ID=$(jq -r '.groups | keys[0]' "$REGISTRY")
    frost dkg coordinator round1 \
        --parallel \
        --storage $STORAGE \
        --timeout $TIMEOUT \
        --registry "$REGISTRY" \
        "${GROUP_ID}"

    section "🔑 Collect Round 2 responses and finalize DKG group.."

    frost dkg coordinator round2 \
        --parallel \
        --storage $STORAGE \
        --timeout $TIMEOUT \
        --registry $REGISTRY \
        "${GROUP_ID}"

    section "🔑 Wait for participants to confirm finalization..."

    frost dkg coordinator finalize \
        --parallel \
        --storage $STORAGE \
        --timeout $TIMEOUT \
        --registry "$REGISTRY" \
        "${GROUP_ID}"

    section "🔑 DKG Complete!"
}

sign() {
    # Placeholder for signing ceremony
}

case "$OPERATION" in
    dkg)
        dkg
        ;;
    sign)
        sign
        ;;
    *)
        echo "Error: Invalid operation '$OPERATION'. Use 'dkg' or 'sign'." >&2
        exit 1
        ;;
esac
